name: x_icon_generator
description: Icon mapping generator
version: 0.0.1+2
homepage: https://github.com/softmarshmallow/remote-ui/tree/master/flutter/packages/x_icon_generator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <2.10.0"

dependencies:
  build: ^2.0.1
  source_gen: ^1.0.0
  analyzer: ^1.5.0

  # region enable this on production
  # x_icon: ^0.0.4
  # endregion

  # region enable this on dev
  x_icon:
    path: ../x_icon
  # endregion

dev_dependencies:
  build_runner: ^2.0.1
